# Generated by Django 5.0.3 on 2024-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_remove_quiz_name_lesson_badge_quiz_badge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
    ]
